services:
  - type: web
    name: ventry-chart-server
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: PORT
        value: 3000
      - key: SUPABASE_URL
        value: https://vpztgavahpgrpnnafmnd.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
